<h2>Add contact using this form</h2>

<?php echo $this->tag->form('signup/register') ?>
<table>


    <tr>
        <td><label for="first_name"> First name:</label></td>
        <td><?php echo $this->tag->textField("first_name") ?></td>
    </tr>
    <tr>
        <td><label for="last_name">Last name:</label></td>
        <td><?php echo $this->tag->textField("last_name") ?></td>
    </tr>
    <tr>
        <td><label for="phone">Phone:</label></td>
        <td><?php echo $this->tag->textField("phone");?></td>
    </tr>
    <tr>
        <td><label for="bio">Bio: </label></td>
        <td><?php echo $this->tag->textField("bio");?></td>
    </tr>
</table>
		<?php echo $this->tag->submitButton("Add") ?>
</form>
<hr>
    <p><?php echo $this->tag->linkTo("","Back")?></p>

